/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/aTurslPLcsQ
 */
import { Label } from "@components/components/ui/label"
import { Textarea } from "@components/components/ui/textarea"
import { Button } from "@components/components/ui/button"

const FortuneTeller = () => {
  return (
    (<div
      className="flex flex-col items-center justify-center bg-black text-white">
      <div className="w-96 h-96 mb-4">
        <video
          alt="Zoltar Arcade Game"
          height="256"
          src="/zoltar-video.mp4"
          style={{
            aspectRatio: "96/96",
            objectFit: "cover",
          }}  
          autoPlay
          />
      </div>
      <h1 className="text-6xl font-bold mb-8 text-red-500">Zoltar Speaks</h1>
      <div
        className="w-full max-w-md p-6 bg-gray-800 rounded-lg shadow-md border-4 border-yellow-500 relative">
        <div className="absolute top-0 left-0 w-full h-full bg-black opacity-50 z-10" />
        <p className="mb-4 text-gray-400 z-20 relative">
          Insert a coin, ask Zoltar a question and get your fortune told.
        </p>
        <div className="flex flex-col space-y-2 z-20 relative">
          <Label htmlFor="question">Your Question</Label>
          <Textarea
            className="min-h-[100px]"
            id="question"
            placeholder="Enter your question here..." />
        </div>
        <Button className="mt-4 bg-yellow-500 text-black z-20 relative">Insert Coin & Ask</Button>
      </div>
      <div className="mt-8 text-sm text-gray-500">
        Disclaimer: This is for entertainment purposes only. No real coins required.
      </div>
    </div>)
  );
}

export default FortuneTeller;