/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3it90zxWrIM
 */
import { Button } from "@components/components/ui/button"

const SelectAgentScreen = () => {
  return (
    (<section
      className="flex flex-col h-screen bg-black text-white relative overflow-x-hidden z-50">
      <div
        className="absolute top-0 left-0 w-full h-20 bg-green-500 bg-opacity-75 flex items-center justify-center py-2 px-4 z-10">
        <p className="text-green-500 text-lg font-mono animate-slide-down">Mission: Embark on a tour of the future</p>
      </div>
      <header className="text-center py-5 bg-gray-800 mt-20">
        <h1 className="text-4xl font-bold">Men In Black: AI Edition</h1>
        <p className="text-lg mt-2 text-green-500 animate-slide-down">Embarking on a tour of the future...</p>
      </header>
      <main
        className="flex-grow overflow-auto p-8 space-y-8 bg-space-pattern bg-cover bg-no-repeat">
        <h2 className="text-3xl mb-8 text-green-500 animate-slide-down">Select Agent</h2>
        <p className="text-lg mb-4 text-green-500 animate-slide-down">
          Agent selection should be based on your knowledge of AI
        </p>
        <div className="grid grid-cols-3 gap-4">
          <div className="flex flex-col items-center group">
            <img
              alt="Agent K"
              className="rounded-full transform group-hover:rotate-360 transition-transform duration-200"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width="200" />
            <h3
              className="text-2xl mt-4 group-hover:text-green-300 transition-colors duration-200">Agent K</h3>
            <p
              className="text-lg mt-2 group-hover:text-green-300 transition-colors duration-200">AI Specialist</p>
            <div className="w-full h-2 bg-gray-500 mt-2">
              <div
                className="h-full bg-green-500"
                style={{
                  width: "80%",
                }} />
            </div>
            <Button
              className="mt-2 bg-gray-500 group-hover:bg-green-500 transition-colors duration-200">Select</Button>
          </div>
          <div className="flex flex-col items-center group">
            <img
              alt="Agent J"
              className="rounded-full transform group-hover:rotate-360 transition-transform duration-200"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width="200" />
            <h3
              className="text-2xl mt-4 group-hover:text-green-300 transition-colors duration-200">Agent J</h3>
            <p
              className="text-lg mt-2 group-hover:text-green-300 transition-colors duration-200">AI Novice</p>
            <div className="w-full h-2 bg-gray-500 mt-2">
              <div
                className="h-full bg-green-500"
                style={{
                  width: "60%",
                }} />
            </div>
            <Button
              className="mt-2 bg-gray-500 group-hover:bg-green-500 transition-colors duration-200">Select</Button>
          </div>
          <div className="flex flex-col items-center group">
            <img
              alt="Agent O"
              className="rounded-full transform group-hover:rotate-360 transition-transform duration-200"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width="200" />
            <h3
              className="text-2xl mt-4 group-hover:text-green-300 transition-colors duration-200">Agent O</h3>
            <p
              className="text-lg mt-2 group-hover:text-green-300 transition-colors duration-200">AI Strategist</p>
            <div className="w-full h-2 bg-gray-500 mt-2">
              <div
                className="h-full bg-green-500"
                style={{
                  width: "90%",
                }} />
            </div>
            <Button
              className="mt-2 bg-gray-500 group-hover:bg-green-500 transition-colors duration-200">Select</Button>
          </div>
        </div>
      </main>
      <footer className="h-14 bg-gray-800 text-center flex items-center justify-center">
        <p className="text-sm">© 2023 Men In Black: AI Edition</p>
      </footer>
      <img
        alt="Hovering Globe"
        className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 opacity-10"
        height="1000"
        src="/placeholder.svg"
        style={{
          aspectRatio: "1000/1000",
          objectFit: "cover",
        }}
        width="1000" />
    </section>)
  );
}

export default SelectAgentScreen;