/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ic56BVWe0pw
 */
import { Button } from "@components/components/ui/button"

const SelectAgentNew = () => {
  return (
    (<section className="flex flex-col h-screen bg-gray-900 text-white relative">
      <div
        className="absolute top-0 left-0 w-full h-20 bg-black bg-opacity-75 flex items-center justify-center overflow-x-scroll whitespace-nowrap py-2 px-4 z-10">
        <p
          className="text-green-500 text-lg font-mono animate-marquee animation-speed-200">
          Mission: Select your character based on your knowledge of AI
        </p>
      </div>
      <header className="text-center py-5 bg-gray-800 mt-20">
        <h1 className="text-4xl font-bold">Elysium Innovations</h1>
        <p className="text-lg mt-2">Entering the future...</p>
      </header>
      <main className="flex-grow overflow-auto p-8">
        <h2 className="text-3xl mb-8">Select Character</h2>
        <p className="text-lg mb-4">Character selection should be based on your knowledge of AI</p>
        <div className="grid grid-cols-2 gap-4">
          <div className="flex flex-col items-center group">
            <img
              alt="Wise Old Man"
              className="rounded-full transform group-hover:scale-110 transition-transform duration-200"
              height={200}
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width={200} />
            <h3
              className="text-2xl mt-4 group-hover:text-yellow-300 transition-colors duration-200">Wise Old Man</h3>
            <p
              className="text-lg mt-2 group-hover:text-yellow-300 transition-colors duration-200">AI Master</p>
            <Button className="mt-2 group-hover:bg-yellow-500 transition-colors duration-200">Select</Button>
          </div>
          <div className="flex flex-col items-center group">
            <img
              alt="Elysium Butler"
              className="rounded-full transform group-hover:scale-110 transition-transform duration-200"
              height={200}
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width={200} />
            <h3
              className="text-2xl mt-4 group-hover:text-yellow-300 transition-colors duration-200">Elysium Butler</h3>
            <p
              className="text-lg mt-2 group-hover:text-yellow-300 transition-colors duration-200">AI Novice</p>
            <Button className="mt-2 group-hover:bg-yellow-500 transition-colors duration-200">Select</Button>
          </div>
          <div className="flex flex-col items-center group">
            <img
              alt="Nick Fury"
              className="rounded-full transform group-hover:scale-110 transition-transform duration-200"
              height={200}
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width={200} />
            <h3
              className="text-2xl mt-4 group-hover:text-yellow-300 transition-colors duration-200">Nick Fury</h3>
            <p
              className="text-lg mt-2 group-hover:text-yellow-300 transition-colors duration-200">AI Enthusiast</p>
            <Button className="mt-2 group-hover:bg-yellow-500 transition-colors duration-200">Select</Button>
          </div>
          <div className="flex flex-col items-center group">
            <img
              alt="Spock"
              className="rounded-full transform group-hover:scale-110 transition-transform duration-200"
              height={200}
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width={200} />
            <h3
              className="text-2xl mt-4 group-hover:text-yellow-300 transition-colors duration-200">Spock</h3>
            <p
              className="text-lg mt-2 group-hover:text-yellow-300 transition-colors duration-200">AI Strategist</p>
            <Button className="mt-2 group-hover:bg-yellow-500 transition-colors duration-200">Select</Button>
          </div>
          <div className="flex flex-col items-center group">
            <img
              alt="Rabbi"
              className="rounded-full transform group-hover:scale-110 transition-transform duration-200"
              height={200}
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width={200} />
            <h3
              className="text-2xl mt-4 group-hover:text-yellow-300 transition-colors duration-200">Rabbi</h3>
            <p
              className="text-lg mt-2 group-hover:text-yellow-300 transition-colors duration-200">AI Scholar</p>
            <Button className="mt-2 group-hover:bg-yellow-500 transition-colors duration-200">Select</Button>
          </div>
          <div className="flex flex-col items-center group">
            <img
              alt="Spongebob"
              className="rounded-full transform group-hover:scale-110 transition-transform duration-200"
              height={200}
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width={200} />
            <h3
              className="text-2xl mt-4 group-hover:text-yellow-300 transition-colors duration-200">Spongebob</h3>
            <p
              className="text-lg mt-2 group-hover:text-yellow-300 transition-colors duration-200">AI Explorer</p>
            <Button className="mt-2 group-hover:bg-yellow-500 transition-colors duration-200">Select</Button>
          </div>
          <div className="flex flex-col items-center group">
            <img
              alt="The Pope"
              className="rounded-full transform group-hover:scale-110 transition-transform duration-200"
              height={200}
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width={200} />
            <h3
              className="text-2xl mt-4 group-hover:text-yellow-300 transition-colors duration-200">The Pope</h3>
            <p
              className="text-lg mt-2 group-hover:text-yellow-300 transition-colors duration-200">AI Ethicist</p>
            <Button className="mt-2 group-hover:bg-yellow-500 transition-colors duration-200">Select</Button>
          </div>
          <div className="flex flex-col items-center group">
            <img
              alt="Gru"
              className="rounded-full transform group-hover:scale-110 transition-transform duration-200"
              height={200}
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width={200} />
            <h3
              className="text-2xl mt-4 group-hover:text-yellow-300 transition-colors duration-200">Gru</h3>
            <p
              className="text-lg mt-2 group-hover:text-yellow-300 transition-colors duration-200">AI Tinkerer</p>
            <Button className="mt-2 group-hover:bg-yellow-500 transition-colors duration-200">Select</Button>
          </div>
        </div>
      </main>
      <footer className="h-14 bg-gray-800 text-center flex items-center justify-center">
        <p className="text-sm">© 2023 Elysium Innovations</p>
      </footer>
    </section>)
  );
}

export default SelectAgentNew